### ISSUE TITLE
File-based whitelisting of licenses/components

### ISSUE THREAD

**Issue by bkimminich** [versioneye/versioneye#643]
Instead of maintaining whitelists on versioneye.com it would be more convenient (and closer to the source) to have the parser evaluate a `.versioneye.yml` file in the project root path:

It might look like this:

```
license_whitelist:
  - MIT
  - Apache 2.0
  - BSD
component_whitelist:
  - group_id: org.apache.httpcomponents
    artifact_id: httpmime
    version: 4.5
  - group_id: junit
    artifact_id: junit
  - group_id: org.mockito
  - language: ruby
    prod_key: rails
    version: 4.0.0
  - language: javascript
    prod_key: twbs/bootstrap
```
